import { useState, useRef, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Send, Zap, FolderOpen, Monitor, Tablet, Smartphone, Download, Code, Eye, Paperclip, Mic, Github } from "lucide-react";
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from "@/components/ui/resizable";
import ReactMarkdown from 'react-markdown';

const hcIcon = '/assets/hc-icon.png';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

interface GeneratedProject {
  name: string;
  type: 'landing' | 'webapp' | 'native';
  files: GeneratedFile[];
  previewHtml?: string;
}

type DeviceType = 'desktop' | 'tablet' | 'mobile';
type ViewMode = 'preview' | 'code';

export default function Workspace() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [isBuilding, setIsBuilding] = useState(false);
  const [device, setDevice] = useState<DeviceType>('desktop');
  const [viewMode, setViewMode] = useState<ViewMode>('preview');
  const [project, setProject] = useState<GeneratedProject | null>(null);
  const [selectedFile, setSelectedFile] = useState(0);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-scroll to bottom of messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      const newHeight = Math.min(Math.max(textarea.scrollHeight, 56), 200);
      textarea.style.height = `${newHeight}px`;
    }
  }, [message]);

  const handleSend = () => {
    if (!message.trim()) return;
    
    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content: message,
      timestamp: new Date(),
    };

    const assistantMessage: Message = {
      id: crypto.randomUUID(),
      role: 'assistant',
      content: '🤔 **Analyzing your request...**\n\nI\'m designing the architecture and creating a build plan. This will just take a moment.',
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage, assistantMessage]);
    setMessage("");
    setIsBuilding(true);

    // Simulate build completion
    setTimeout(() => {
      setIsBuilding(false);
      // Demo: Generate a sample project
      setProject({
        name: 'Generated Project',
        type: 'landing',
        files: [
          {
            path: 'index.html',
            language: 'html',
            content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Project</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen flex items-center justify-center">
  <div class="text-center">
    <h1 class="text-4xl font-bold mb-4">🚀 Your Project</h1>
    <p class="text-gray-400">Generated by HeftCoder AI</p>
  </div>
</body>
</html>`
          },
          {
            path: 'styles.css',
            language: 'css',
            content: `/* Custom styles */
body {
  font-family: system-ui, sans-serif;
}`
          }
        ],
        previewHtml: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Project</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white min-h-screen flex items-center justify-center">
  <div class="text-center">
    <h1 class="text-4xl font-bold mb-4">🚀 Your Project</h1>
    <p class="text-gray-400">Generated by HeftCoder AI</p>
  </div>
</body>
</html>`
      });

      const completeMessage: Message = {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: '✅ **Build Complete!**\n\nYour project has been generated successfully. Check the preview panel to see the result.',
        timestamp: new Date(),
      };
      setMessages(prev => [...prev, completeMessage]);
    }, 3000);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="h-screen flex flex-col bg-background text-foreground">
      {/* Top Nav */}
      <header className="h-14 border-b border-border bg-card flex items-center justify-between px-4">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate("/")}
            className="p-2 hover:bg-secondary rounded-lg transition-colors"
          >
            <ArrowLeft size={20} />
          </button>
          <div className="flex items-center gap-2">
            <img src={hcIcon} alt="HeftCoder" className="h-8 w-8 rounded-lg" />
            <span className="text-lg font-semibold">HeftCoder</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button className="p-2 hover:bg-secondary rounded-lg transition-colors">
            <FolderOpen size={20} />
          </button>
          <button className="p-2 hover:bg-secondary rounded-lg transition-colors">
            <Github size={20} />
          </button>
          <button className="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg font-medium transition-colors">
            Publish
          </button>
        </div>
      </header>

      {/* Main Content */}
      <ResizablePanelGroup direction="horizontal" className="flex-1">
        {/* Chat Panel */}
        <ResizablePanel defaultSize={40} minSize={25} maxSize={55}>
          <div className="h-full flex flex-col bg-card">
            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {messages.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full text-center">
                  <h2 className="text-2xl font-bold mb-2">What would you like to build?</h2>
                  <p className="text-muted-foreground max-w-md">
                    Describe your project and I'll help you create it. I can build web apps,
                    APIs, landing pages, dashboards, and more.
                  </p>
                </div>
              ) : (
                messages.map((msg) => (
                  <div 
                    key={msg.id} 
                    className={`p-4 rounded-xl ${
                      msg.role === 'user' 
                        ? 'bg-primary/20 ml-8 border border-primary/30' 
                        : 'bg-secondary mr-8'
                    }`}
                  >
                    <div className="prose prose-sm prose-invert max-w-none">
                      <ReactMarkdown>
                        {msg.content}
                      </ReactMarkdown>
                    </div>
                  </div>
                ))
              )}
              <div ref={messagesEndRef} />
            </div>
            
            {/* Input */}
            <div className="p-4 border-t border-border">
              <div className="flex flex-col gap-3 p-3 bg-input rounded-xl border border-border focus-within:border-primary/50 focus-within:ring-1 focus-within:ring-primary/30 transition-all">
                <textarea
                  ref={textareaRef}
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Message HeftCoder..."
                  className="w-full min-h-[56px] max-h-[200px] resize-none bg-transparent border-0 text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-0 text-base leading-relaxed"
                  rows={1}
                  disabled={isBuilding}
                />
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors text-muted-foreground hover:text-foreground">
                      <Paperclip size={18} />
                    </button>
                    <div className="flex items-center gap-2 px-3 py-2 bg-secondary rounded-lg text-sm text-muted-foreground border border-primary/30 shadow-[0_0_15px_rgba(255,140,0,0.3),0_0_30px_rgba(255,140,0,0.15)]">
                      <img src={hcIcon} alt="HeftCoder" className="h-6 w-6 rounded" />
                      <span className="text-foreground font-medium">agents</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors text-muted-foreground hover:text-foreground">
                      <Mic size={18} />
                    </button>
                    <button 
                      onClick={handleSend}
                      disabled={!message.trim() || isBuilding}
                      className="p-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Send size={18} />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </ResizablePanel>

        <ResizableHandle className="w-1.5 bg-border hover:bg-primary/50 transition-colors data-[resize-handle-active]:bg-primary" />

        {/* Preview Panel */}
        <ResizablePanel defaultSize={60} minSize={45} maxSize={75}>
          <div className="h-full flex flex-col bg-background">
            {/* Preview Toolbar */}
            <div className="h-12 border-b border-border px-4 flex items-center justify-between bg-card/50">
              <div className="flex items-center gap-2">
                {/* View Mode Toggle */}
                <div className="flex items-center bg-secondary rounded-lg p-1">
                  <button 
                    onClick={() => setViewMode('preview')}
                    className={`flex items-center gap-1 px-3 py-1.5 rounded text-sm font-medium transition-colors ${
                      viewMode === 'preview' ? 'bg-background text-foreground' : 'text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    <Eye size={14} />
                    Preview
                  </button>
                  <button 
                    onClick={() => setViewMode('code')}
                    className={`flex items-center gap-1 px-3 py-1.5 rounded text-sm font-medium transition-colors ${
                      viewMode === 'code' ? 'bg-background text-foreground' : 'text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    <Code size={14} />
                    Code
                  </button>
                </div>

                {/* Device Selector (only in preview mode) */}
                {viewMode === 'preview' && (
                  <div className="flex items-center gap-1 bg-secondary rounded-lg p-1 ml-2">
                    <button 
                      onClick={() => setDevice('desktop')}
                      className={`p-2 rounded transition-colors ${device === 'desktop' ? 'bg-background' : 'hover:bg-background/50'}`}
                    >
                      <Monitor size={16} />
                    </button>
                    <button 
                      onClick={() => setDevice('tablet')}
                      className={`p-2 rounded transition-colors ${device === 'tablet' ? 'bg-background' : 'hover:bg-background/50'}`}
                    >
                      <Tablet size={16} />
                    </button>
                    <button 
                      onClick={() => setDevice('mobile')}
                      className={`p-2 rounded transition-colors ${device === 'mobile' ? 'bg-background' : 'hover:bg-background/50'}`}
                    >
                      <Smartphone size={16} />
                    </button>
                  </div>
                )}
              </div>

              {project && (
                <button className="p-2 hover:bg-secondary rounded-lg transition-colors text-muted-foreground hover:text-foreground">
                  <Download size={18} />
                </button>
              )}
            </div>

            {/* Preview Content */}
            <div className="flex-1 flex items-center justify-center">
              {isBuilding ? (
                <div className="flex flex-col items-center justify-center">
                  <div className="relative mb-8">
                    <div className="absolute inset-0 bg-primary/30 blur-3xl rounded-full scale-150 animate-pulse" />
                    <img
                      src={hcIcon}
                      alt="HeftCoder"
                      className="relative w-24 h-24 rounded-2xl animate-pulse"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xl font-medium">Building your project</span>
                    <div className="flex gap-1">
                      <span className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                  <p className="text-muted-foreground mt-2 text-sm">Preview will appear when ready...</p>
                </div>
              ) : project ? (
                viewMode === 'preview' ? (
                  <div className="h-full w-full flex items-center justify-center bg-[#1a1a1a] p-4">
                    <div 
                      className={`bg-white rounded-lg shadow-2xl overflow-hidden transition-all duration-300 ${
                        device !== 'desktop' ? 'border-8 border-gray-800 rounded-3xl' : ''
                      }`}
                      style={{ 
                        width: device === 'desktop' ? '100%' : device === 'tablet' ? '768px' : '375px', 
                        height: device === 'desktop' ? '100%' : device === 'tablet' ? '1024px' : '667px',
                        maxWidth: '100%',
                        maxHeight: '100%'
                      }}
                    >
                      <iframe
                        srcDoc={project.previewHtml}
                        title="Project Preview"
                        className="w-full h-full border-0"
                        sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
                      />
                    </div>
                  </div>
                ) : (
                  <div className="h-full w-full flex">
                    {/* File list */}
                    <div className="w-48 bg-secondary/50 border-r border-border overflow-y-auto">
                      <div className="p-2 text-xs text-muted-foreground font-medium uppercase tracking-wider">
                        Files
                      </div>
                      {project.files.map((file, index) => (
                        <button
                          key={file.path}
                          onClick={() => setSelectedFile(index)}
                          className={`w-full text-left px-3 py-2 text-sm truncate transition-colors ${
                            selectedFile === index 
                              ? 'bg-primary/20 text-primary' 
                              : 'text-muted-foreground hover:bg-secondary hover:text-foreground'
                          }`}
                        >
                          {file.path}
                        </button>
                      ))}
                    </div>
                    
                    {/* Code content */}
                    <div className="flex-1 overflow-auto bg-black/40 p-4">
                      <pre className="text-sm font-mono text-foreground/90 whitespace-pre-wrap">
                        <code>{project.files[selectedFile]?.content}</code>
                      </pre>
                    </div>
                  </div>
                )
              ) : (
                <div className="text-center">
                  <div className="mb-6 opacity-60">
                    <img
                      src={hcIcon}
                      alt="HeftCoder"
                      className="w-20 h-20 rounded-2xl mx-auto"
                    />
                  </div>
                  <p className="text-lg text-muted-foreground max-w-md">
                    Your project preview will appear here once generation starts
                  </p>
                </div>
              )}
            </div>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}
